line:
 bot:
  channel-token: "y9mFe+GnkzDrIL2pGQlRKdJIr9bvg+eRjkmwRRFToFeYjLGNk2XOI7TB70fL654s4Q2qU3fIavtlZPwBK/zL7V08TeOHdu5iHxIzEsTGNk/71mPuioLAdhOCXQvDLsIq0wou1ehG++08DoZ9VCxvHgdB04t89/1O/w1cDnyilFU="
  channel-secret: "4752d93e8c98de1f44f1eb554e5a8507"
  handler.path: /callback