line.bot:
  channel-token: '{ojuFS52slaABLHSN5iao9JgLahAtdjdS1vrMFwrJuBk5nxUlzn3br1vUfqFLc4yR4Q2qU3fIavtlZPwBK / zL7V08TeOHdu5iHxIzEsTGNk / PSjjyetKxIazZpEw1}'
  channel-secret: '{4752d93e8c98de1f44f1eb554e5a8507}'
  handler.path: /callback